# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import feature_server_pb2 as feature__server__pb2


class FeatureServerStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Collect = channel.unary_unary(
                '/feature_server.FeatureServer/Collect',
                request_serializer=feature__server__pb2.CollectRequest.SerializeToString,
                response_deserializer=feature__server__pb2.CollectReply.FromString,
                )


class FeatureServerServicer(object):
    """The greeting service definition.
    """

    def Collect(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FeatureServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Collect': grpc.unary_unary_rpc_method_handler(
                    servicer.Collect,
                    request_deserializer=feature__server__pb2.CollectRequest.FromString,
                    response_serializer=feature__server__pb2.CollectReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'feature_server.FeatureServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FeatureServer(object):
    """The greeting service definition.
    """

    @staticmethod
    def Collect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/feature_server.FeatureServer/Collect',
            feature__server__pb2.CollectRequest.SerializeToString,
            feature__server__pb2.CollectReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
