# https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html

package:
  name: torch-quiver
  version: 0.1.2

source:
  path: ../..

requirements:
  host:
    - pip
    - python {{ environ.get('PYTHON_VERSION') }}

  run:
    - python {{ environ.get('PYTHON_VERSION') }}
    - {{ environ.get('CONDA_PYTORCH_CONSTRAINT') }}
    - {{ environ.get('CONDA_CUDATOOLKIT_CONSTRAINT') }}
    - pytorch-scatter
    - pytorch-sparse
    - pytorch-cluster
    - pytorch-spline-conv
    - pyg
    - networkx>=2.4
    - tqdm
    - jinja2
    - pyparsing
    - yacs
    - PyYAML
    - scikit-learn
    - python-louvain
    - pandas
    - requests
    - numpy

build:
  string: py{{ environ.get('PYTHON_VERSION').replace('.', '') }}_torch_{{ environ['TORCH_VERSION'] }}_{{ environ['CUDA_VERSION'] }}
  script: pip install --no-index -U .

test:
  imports:
    - torch.utils
    - torch_scatter
    - torch_sparse
    - torch_cluster
    - torch_spline_conv
    - torch_geometric
    - torch_geometric.nn
    - torch_geometric.data
    - torch_geometric.utils
    - torch_geometric.datasets
    - torch_geometric.transforms

about:
  home: https://github.com/quiver-team/torch-quiver
  license: MIT
  summary: distributed Graph Neural Network Library for PyTorch
